DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS registrations;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS trainers;
DROP TABLE IF EXISTS studios;
DROP TABLE IF EXISTS gyms;

DROP TYPE IF EXISTS access_type;
DROP TYPE IF EXISTS membership_tier_type;
DROP TYPE IF EXISTS registration_status_type;
DROP TYPE IF EXISTS day_type;